//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DistCommands.rc
//
#define IDOK3                           3
#define ID_PREVIEW                      3
#define IDOK2                           5
#define IDCANCEL2                       6
#define IDS_PROJNAME                    100
#define IDS_FTPTRANSFER_FILESTATUS1     102
#define IDS_FTPTRANSFER_CONNECTED       103
#define IDS_FTPTRANSFER_RESOLVING_NAME  104
#define IDS_FTPTRANSFER_RESOLVED_NAME   105
#define IDS_FTPTRANSFER_CONNECTING      106
#define IDS_FTPTRANSFER_FAIL_OPEN_FILE  107
#define IDS_FTPTRANSFER_GETTING_FILE_INFORMATION 108
#define IDS_FTPTRANSFER_FILESTATUS2     109
#define IDS_FTPTRANSFER_GENERIC_ERROR   110
#define IDS_FTPTRANSFER_FAIL_CONNECT_SERVER 111
#define IDS_FTPTRANSFER_INVALID_SERVER_RESPONSE 112
#define IDS_TRANSFER_OK_TO_OVERWRITE    113
#define IDS_FTPTRANSFER_ERROR_READFILE  114
#define IDS_FTPTRANSFER_PERCENTAGE      115
#define IDS_FTPTRANSFER_RETREIVEING_FILE 116
#define IDS_FTPTRANSFER_OF              117
#define IDS_FTPTRANSFER_SECONDS         118
#define IDS_FTPTRANSFER_MINUTES         119
#define IDS_FTPTRANSFER_MINUTES_AND_SECONDS 120
#define IDS_FTPTRANSFER_BYTES           121
#define IDS_FTPTRANSFER_UPLOADING_FILE  122
#define IDS_FTPTRANSFER_KILOBYTES       123
#define IDS_FTPTRANSFER_ERROR_WRITEFILE 124
#define IDS_FTPTRANSFER_MEGABYTES       125
#define IDS_FTPTRANSFER_TIMELEFT        127
#define IDS_FTPTRANSFER_BYTESPERSECOND  128
#define IDS_FTPTRANSFER_KILOBYTESPERSECOND 129
#define IDS_FTPTRANSFER_OK_TO_OVERWRITE 130
#define IDS_FTPTRANSFER_FAIL_LOCALFILE_OPEN1 131
#define IDS_FTPTRANSFER_ABORTING_TRANSFER 132
#define IDS_FTPTRANSFER_FAIL_LOCALFILE_OPEN2 133
#define IDS_FTPTRANSFER_UPLOAD_CAPTION  134
#define IDD_DLG_READINFO                200
#define IDC_TREE1                       200
#define IDC_TREE_OBJECT                 200
#define IDC_TAB_OPTIONS                 200
#define IDC_TREE                        200
#define IDC_SPLITTERBAR                 201
#define IDC_STATIC_FRAMESTYLE           201
#define IDC_LIST_FRAMESTYLE             202
#define IDC_SAVE                        202
#define IDC_LIST_NORTHCOMPASS           203
#define IDC_COMBO1                      203
#define IDC_STATIC_NORTHCOMPASS         204
#define IDC_COMBO2                      204
#define ID_PLOT                         205
#define IDC_COMBO3                      205
#define IDC_EDIT1                       206
#define IDD_FTPTRANSFER                 207
#define IDC_EDIT2                       207
#define IDR_FTPDOWNLOAD_ANIMATION       208
#define IDC_EDIT3                       208
#define IDR_FTPUPLOAD_ANIMATION         209
#define IDC_EDIT4                       209
#define IDC_STATIC_NORMAL               210
#define IDC_EDIT5                       210
#define IDC_STATIC_SCALE                211
#define IDD_DLG_PLOTSETTING             211
#define IDC_EDIT6                       211
#define IDC_STATIC_TITLE                212
#define IDD_DIALOG_GONGSHI              212
#define IDC_EDIT7                       212
#define IDD_DLG_GONGSHI                 212
#define IDC_EDIT_TITLE                  213
#define IDC_EDIT8                       213
#define IDD_DLG_GONGSHI2                213
#define IDC_COMBO_FRAMESIZE             214
#define IDC_EDIT9                       214
#define IDD_DLG_GONGSHI3                214
#define IDC_STATIC_FRAMESIZE            215
#define IDC_EDIT10                      215
#define IDC_EDIT_COMPANY                216
#define IDC_EDIT11                      216
#define IDD_TK_SEL                      216
#define IDC_STATIC_COMPANY              217
#define IDC_EDIT12                      217
#define IDC_COMBO_CUTFRAME              218
#define IDC_EDIT13                      218
#define IDD_TK_GONGCHENG                218
#define IDC_STATIC_CUTFRAME             219
#define IDC_EDIT14                      219
#define IDD_TK_YONGDI                   219
#define IDC_RADIO_PRINTSIZE             220
#define IDC_DATETIMEPICKER1             220
#define IDD_DLG_UPLOADDWGFILEEX         220
#define IDC_RADIO_CURRENTSIZE           221
#define IDC_DATETIMEPICKER2             221
#define IDC_CHECK_ADDCOMPANY            222
#define IDC_COMBO4                      222
#define IDD_DLG_EDITDESC                222
#define IDC_CHECK_ADDDATETEXT           223
#define IDC_EDT_BICODE                  223
#define IDC_COMBO5                      223
#define IDD_DLG_EDITLOG                 223
#define IDC_EDIT_SCALE                  224
#define IDC_EDT_BIOWNER                 224
#define IDC_COMBO6                      224
#define IDD_DLG_HISTORY                 224
#define IDC_EDT_FILE                    225
#define IDC_COMBO7                      225
#define IDD_DLG_EDITLOG2                225
#define IDC_CHECK_ADDCOMPASS            226
#define IDC_BTN_BROWSE                  226
#define IDD_ATTRIBUTE                   226
#define IDC_EDT_FILENAME_EX             227
#define IDC_BTN_BROWSE_EX               228
#define IDC_STATIC_EX                   229
#define IDC_EDIT15                      230
#define IDC_BTN_DELETE_EX               232
#define IDC_LIST2                       233
#define IDC_FILELIST                    233
#define IDC_BTN_SHOWLOG                 234
#define IDC_EDT_NAME                    235
#define IDC_EDT_DESC                    236
#define IDC_LIST_LOG                    237
#define IDC_CHECK_SHOWALL               238
#define IDC_DATETIMEPICKER              239
#define IDC_LIST_VIEWLOG                241
#define IDC_LIST_XDATA                  252
#define IDC_COMBO_CADLY                 253
#define IDC_LIST_OBJ                    254
#define IDC_BTN_SELECT                  255
#define IDC_ANIMATE1                    1000
#define IDC_STATUS                      1001
#define IDC_FILESTATUS                  1002
#define IDC_PROGRESS1                   1003
#define IDC_TIMELEFT                    1004
#define IDC_TRANSFER_RATE               1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         242
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
